### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by kg-kartik** [kg-kartik/Ambulance-on-demand#10]
Login and Signup screens needs to be implemented.
Signup component will have input fields for name, email address, phone, password and Login component will have input fields for email and passwords.
UI needs to be more of neat and clean.

**Comment by prabhu4444** [comment]
I'd like to contribute, what should I do? @kg-kartik

**Comment by Areeb786123** [comment]
i would like to contribute

**Comment by agatharejina** [comment]
Hi! what should I do to contribute?

**Comment by kg-kartik** [comment]
Basically you need to make two React Components (Login and Signup, only UI part) with fields mentioned above.
It would be good if you can make something like form in this 
https://hackathon-an.herokuapp.com/signup
It would be good to have a svg type in half side of the site !

If you understand what are the requirements then you may start working and i will assign you this issue and then make a pull request.
Best UI Will be accepted

**Comment by EnechukwuChibuike** [comment]
I will do it

**Comment by EnechukwuChibuike** [comment]
> Basically you need to make two React Components (Login and Signup, only UI part) with fields mentioned above.
> It would be good if you can make something like form in this
> https://hackathon-an.herokuapp.com/signup
> It would be good to have a svg type in half side of the site !
> 
> If you understand what are the requirements then you may start working and i will assign you this issue and then make a pull request.
> Best UI Will be accepted

Assign it to me

**Comment by agatharejina** [comment]
> Basically you need to make two React Components (Login and Signup, only UI part) with fields mentioned above.
> It would be good if you can make something like form in this
> https://hackathon-an.herokuapp.com/signup
> It would be good to have a svg type in half side of the site !
> 
> If you understand what are the requirements then you may start working and i will assign you this issue and then make a pull request.
> Best UI Will be accepted

I can do it too :) will much appreciate it if you could assign it to me

**Comment by harshalkaigaonkar** [comment]
is the issue open or assigned ?

**Comment by kg-kartik** [comment]
Thanks everyone for showing so much interest..I guess if everyone is fine with working on the issue independently and raising a PR , so that i can then select the best UI among them, that would be good!

**Comment by kg-kartik** [comment]
@agatharejina thanks for raising the PR , I really liked your work.
Others , I have more features to be added in the same application , so i will be raising more issues in some while.
As of now , I am closing this issue.
Thanks!
