### ISSUE TITLE
Api route needed for geocoding

### ISSUE THREAD

**Issue by kg-kartik** [kg-kartik/Ambulance-on-demand#13]
An api route is to be made which takes street address and converts it to geographic coordinates(latitude and longitude)

**Comment by yerlantemir** [comment]
Hi! I want to work on it, could you assign me ?

**Comment by kg-kartik** [comment]
Yea sure I guess you would have more of got what is to be done. So i am assigning you the issue, feel free to raise a PR and ping in case of any doubts !
