### ISSUE TITLE
Authentication system for ambulance to be implemented

### ISSUE THREAD

**Issue by kg-kartik** [kg-kartik/Ambulance-on-demand#8]
Currently, the ambulance data has been hard coded. Backend for Ambulance Auth system is required where ambulance can enter basic information (name,email address,phone number) and street address .
The auth system should include signup and signin routes.
Signup route with basic information as stated above and signin route with phone/email and password.

**Comment by GabriellaAmah** [comment]
Can i work on this?

**Comment by kg-kartik** [comment]
> Can i work on this?

Yea surely, I guess you would have got more of the idea how to do. So, I am assigning you the issue,
for further doubts you can ask here!
