### ISSUE TITLE
Add GitHub Repo Links to the site

### ISSUE THREAD

**Issue by kg-kartik** [kg-kartik/Ambulance-on-demand#9]
A "Star us on GitHub" and "Fork us on Github" button need to be added in the web application without disturbing the styling and working of the application.
It would help newcomers to contribute to the project by directly staring and forking the repo.

**Comment by priyanshupardhi** [comment]
Hey @kg-kartik  can I contribute?

**Comment by saaheel** [comment]
Can I contribute to this?

**Comment by kg-kartik** [comment]
> Hey @kg-kartik can I contribute?

Yea sure I guess you would have got what needs to be added in the documentation. So i am assigning you the issue, feel free to raise a PR and ping in case of any doubts !

**Comment by kg-kartik** [comment]
> Can I contribute to this?

Hey sorry, but I already assigned the issue, though you can clone the repo and see what can be improved further and can then raise the issue for the same !

**Comment by saaheel** [comment]
> > Can I contribute to this?
> 
> Hey sorry, but I already assigned the issue, though you can clone the repo and see what can be improved further and can then raise the issue for the same !

Sure. Thanks

**Comment by priyanshupardhi** [comment]
@saaheel  go on
